language: scala
scala:
  - "2.10.3"
jdk:
  - oraclejdk7
  
env:
  - NEO_VERSION="2.0.0"

script:
  - sbt package
  - ./install_at_path.sh neo4j-community-$NEO_VERSION
  - neo4j-community-$NEO_VERSION/bin/neo4j start
  - cat neo4j-community-$NEO_VERSION/data/graph.db/messages.log
  - go test 

before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - echo "org.neo4j.server.thirdparty_jaxrs_classes=acl=/acl" >> neo4j-community-$NEO_VERSION/conf/neo4j-server.properties
