language: scala
scala:
  - "2.10.3"
jdk:
  - oraclejdk7
  
env:
  - NEO_VERSION="2.0.0"

script:
  - sbt package
  - cp target/scala*/neo4acl*.jar neo4j-community-$NEO_VERSION/lib/
  - neo4j-community-$NEO_VERSION/bin/neo4j start
  - wget http://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar -P neo4j-community-$NEO_VERSION/lib/
  - wget http://repo1.maven.org/maven2/net/liftweb/lift-json_2.10/2.5.1/lift-json_2.10-2.5.1.jar -P neo4j-community-$NEO_VERSION/lib/
  - go test 

before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - echo "org.neo4j.server.thirdparty_jaxrs_classes=neo4ACL=/acl" >> neo4j-community-$NEO_VERSION/conf/neo4j-server.properties
